# Generated by Django 6.0.3 on 2026-04-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='descriptions',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='value',
            new_name='valor',
        ),
    ]
