# Generated by Django 6.0.3 on 2026-04-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_date_receita_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='valor',
            new_name='value',
        ),
    ]
